name: kixpro-backend

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-server
    ports:
      - '3001:3000'
    command: sh -c "npx typeorm migration:run -d dist/config/data-source.config.js && node dist/main.js"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:password@database:5432/kixpro?sslmode=disable   # ← fixed
       # JWT
      - JWT_SECRET=Tgw1MWEhKIOU7MIhLkBlhtWXSODwWqPyEIuG
      - JWT_TOKEN_AUDIENCE=myapp-users
      - JWT_TOKEN_ISSUER=myapp-auth-service
      - JWT_ACCESS_TOKEN_TTL=15m
      - JWT_REFRESH_TOKEN_TTL=7d
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  database:
    image: postgres:16-alpine
    container_name: my-app-postgres
    environment:
      POSTGRES_DB: kixpro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:   
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: