POST  http://localhost:3000/users
Content-Type: application/json

{
    "firstName":"rabiul",
    "lastName":"hasan",
    "email":"rabiul@gmail.com",
    "password":"Password123#",
    "isAuth":true
    }
