POST  http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  
    "firstName":"rabiul",
    "lastName":"hasan",
    "email":"mdrabiulkhanbabo@gmail.com",
    "password":"Password123#"
  
    
  
    }
